name: Video Converter CI

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/ci.yml'
      - '.github/workflows/build-jobs.yml'

permissions:
  contents: read
  actions: write

jobs:
  build:
    name: Build Frontend and Backend
    uses: ./.github/workflows/build-jobs.yml
