name: Video Converter CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/ci.yml'
      - '.github/workflows/build-jobs.yml'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: write

jobs:
  build:
    name: Build Frontend and Backend
    uses: ./.github/workflows/build-jobs.yml
