name: Video Converter - CI

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/ci.yml'
      - '.github/workflows/build-jobs.yml'

permissions:
  contents: read

jobs:
  build:
    name: Full Build
    uses: ./.github/workflows/build-jobs.yml
