name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read # Needed for checkout, lint, format check, build, test
  actions: write # Needed for cache write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.2
          working-directory: ./backend

      - name: Check formatting
        run: test -z "$(gofmt -l .)"

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...
